id = "rsml"
name = "RSML"
description = "Support for RSML (Roblox Style Management Language)"
version = "0.0.2"
schema_version = 1
authors = ["rbx-rsml"]
repository = "https://github.com/rbx-rsml/rsml-lsp"

[grammars.rsml]
repository = "https://github.com/rbx-rsml/tree-sitter-rsml"
commit = "4c3e60c1fea59f7b5fc99edba12dbce3488c446c"

[language_servers.rsml-lsp]
name = "RSML LSP"
languages = ["RSML"]
