name: Release

#on:
#  push:
#    tags: ["v*"]

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  #create-release:
  #  name: Create Release
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Create Release
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      run: |
  #        gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }}

  build_lsp:
    #needs: ["create-release"]
    strategy:
      fail-fast: false
      matrix:
        # https://doc.rust-lang.org/rustc/platform-support.html
        include:
          #- host: linux
          #  os: ubuntu-latest
          #  target: x86_64-unknown-linux-gnu
          #  label: linux-x86_64

          #- host: windows
          #  os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #  label: windows-x86_64

          #- host: macos
          #  os: macos-latest
          #  target: x86_64-apple-darwin
          #  label: macos-x86_64

          - host: macos
            os: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      BIN: rsml-lsp
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          save-always: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --locked --verbose --target ${{ matrix.target }}
        env:
          # Build into a known directory so we can find our build artifact more
          # easily.
          CARGO_TARGET_DIR: output

      - name: Upload Rust Cache as Artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: rust-cache-${{ matrix.os }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

      - name: Generate File Stem
        shell: bash
        run: |
          echo "FILE_STEM=$BIN-${{ matrix.label }}" >> "$GITHUB_ENV"

      - name: Generate Artifact Name
        shell: bash
        run: |
          echo "ARTIFACT_NAME=$BIN-server-${{ matrix.label }}.zip" >> "$GITHUB_ENV"

      - name: Create Archive
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir staging

          if [ "${{ matrix.host }}" = "windows" ]; then
            cp "output/${{ matrix.target }}/release/$BIN.exe" staging/
            cd staging
            mv $BIN.exe $FILE_STEM.exe
            7z a ../$ARTIFACT_NAME *
          else
            cp "output/${{ matrix.target }}/release/$BIN" staging/
            cd staging
            mv $BIN $FILE_STEM
            zip ../$ARTIFACT_NAME *
          fi

      - name: Upload Archive to Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ARTIFACT_NAME }}
          name: ${{ env.ARTIFACT_NAME }}

  build_vscode:
    needs: ["build_lsp"]
    name: Build VS Code
    runs-on: ubuntu-latest
    env:
      BIN: rsml-lsp-vscode
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download LSP Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create Destination
        run: mkdir -p extensions/vscode/server

      - name: Extract Artifacts To Destination
        run: |
          for archive in ./downloaded-artifacts/**/*.zip; do
            unzip -o "$archive" -d extensions/vscode/server
          done
      
      - name: Generate Artifact Name
        shell: bash
        run: |
          echo "ARTIFACT_NAME=$BIN.zip" >> "$GITHUB_ENV"

      - name: Create Archive
        shell: bash
        run: |
          cd extensions/vscode
          zip -r ../../${{ env.ARTIFACT_NAME }} *
      

      - name: Upload VSCode LSP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ARTIFACT_NAME }}
          name: ${{ env.ARTIFACT_NAME }}

